### ISSUE TITLE
Not working for me

### ISSUE THREAD

**Issue by urbels** [mattiasgeniar/varnish-5.0-configuration-templates#1]
● varnish.service - Varnish Cache, a high-performance HTTP accelerator
   Loaded: loaded (/lib/systemd/system/varnish.service; disabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Fri 2016-12-16 15:00:19 UTC; 9s ago
  Process: 15812 ExecStart=/usr/sbin/varnishd -a :6081 -T localhost:6082 -f /etc/varnish/default.vcl -S /etc/varnish/secret -s malloc,256m (code=exited, status=2)

Dec 16 15:00:19 proxima varnishd[15812]: sub vcl_hit {
Dec 16 15:00:19 proxima varnishd[15812]: ----#######--
Dec 16 15:00:19 proxima varnishd[15812]: ...which is the "vcl_hit" method
Dec 16 15:00:19 proxima varnishd[15812]: Legal returns are: "deliver" "miss" "pass" "restart" "synth"
Dec 16 15:00:19 proxima varnishd[15812]: Running VCC-compiler failed, exited with 2
Dec 16 15:00:19 proxima varnishd[15812]: VCL compilation failed
Dec 16 15:00:19 proxima systemd[1]: varnish.service: Control process exited, code=exited status=2
Dec 16 15:00:19 proxima systemd[1]: Failed to start Varnish Cache, a high-performance HTTP accelerator.
Dec 16 15:00:19 proxima systemd[1]: varnish.service: Unit entered failed state.
Dec 16 15:00:19 proxima systemd[1]: varnish.service: Failed with result 'exit-code'.

**Comment by mattiasgeniar** [comment]
Looks like the deprecation in https://varnish-cache.org/docs/trunk/users-guide/vcl-built-in-subs.html has been put in effect, can you try again with the latest release?

**Comment by urbels** [comment]
It works! Thanks!
