### ISSUE TITLE
commands for cookies is not vaild for version 5

### ISSUE THREAD

**Issue by aelsharawi** [mattiasgeniar/varnish-5.0-configuration-templates#3]
https://ma.ttias.be/varnish-tip-see-cookies-stripped-vcl/

is not working for varnish 5

it shows:
`varnishlog: invalid option -- 'm'
Usage: varnishlog <options>

Options:
 [-a]                      Append to file
 [-A]                      Text output
 [-b]                      Only display backend records
 [-c]                      Only display client records
 [-C]                      Caseless regular expressions
 [-d]                      Process old log entries and exit
 [-D]                      Daemonize
 [-g <session|request|vxid|raw>] Grouping mode (default: vxid)
 [-h]                      Usage help
 [-i <taglist>]            Include tags
 [-I <[taglist:]regex>]    Include by regex
 [-k <num>]                Limit transactions
 [-L <limit>]              Incomplete transaction limit
 [-n <dir>]                varnishd working directory
 [-N <filename>]           VSM filename
 [-P <file>]               PID file
 [-q <query>]              VSL query
 [-r <filename>]           Binary file input
 [-t <seconds|off>]        VSM connection timeout
 [-T <seconds>]            Transaction end timeout
 [-v]                      Verbose record printing
 [-V]                      Version
 [-w <filename>]           Output filename
 [-x <taglist>]            Exclude tags
 [-X <[taglist:]regex>]    Exclude by regex`

**Comment by vahidalvandi** [comment]
it work fine in varnish 6
