### ISSUE TITLE
Varnish not working with ssl

### ISSUE THREAD

**Issue by keevitaja** [mattiasgeniar/varnish-5.0-configuration-templates#4]
Hello!

Is it possible to get varnish working with SSL?

Or is it not using https?

**Comment by pothi** [comment]
Some background info:

- https://varnish-cache.org/docs/trunk/phk/ssl.html
- https://varnish-cache.org/docs/trunk/phk/ssl_again.html

> Is it possible to get varnish working with SSL?

Yes, it is possible, even though there isn't built-in support for SSL in Varnish.

**Comment by mattiasgeniar** [comment]
Yes, but not in Varnish: you'll need either Hitch or Nginx to act as a reverse proxy in front of Varnish.

Varnish itself has no direct support for SSL.
