### ISSUE TITLE
Miss hit on CTRL-F5

### ISSUE THREAD

**Issue by tomadmiraal** [mattiasgeniar/varnish-5.0-configuration-templates#6]
I love the script! works perfect, except on one thing:

When I push CTRL-F5 I always get a miss-hit.

Is this normal?

**Comment by mattiasgeniar** [comment]
This is determined by this logic: https://github.com/mattiasgeniar/varnish-5.0-configuration-templates/blob/master/default.vcl#L147-L156 

If you don't want that behaviour, either remove that block entirely, or make sure the `acl` for the `purge` is set to only include the IPs that you want to allow purges from.
